version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: timesheet-postgres-test
    environment:
      POSTGRES_DB: timesheet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - timesheet-test-network

volumes:
  postgres_test_data:

networks:
  timesheet-test-network:
    driver: bridge 