services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: timesheet-postgres
    environment:
      POSTGRES_DB: timesheet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - timesheet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak Authentication Server
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: timesheet-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_PORT: 9000
      KC_FEATURES: preview
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - timesheet-network
    command: ["start-dev", "--http-port=9000", "--hostname-strict=false"]

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timesheet-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: timesheet_db
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      JWT_EXPIRES_IN: 24h
      KEYCLOAK_URL: http://localhost:9000
      KEYCLOAK_REALM: timesheet-realm
      KEYCLOAK_CLIENT_ID: timesheet-client
      KEYCLOAK_CLIENT_SECRET: your-keycloak-client-secret
      APP_PORT: 3000
      NODE_ENV: development
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - timesheet-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  postgres_data:

networks:
  timesheet-network:
    driver: bridge
